# Generated by Django 5.0.6 on 2024-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=121)),
                ('email', models.CharField(max_length=121)),
                ('password', models.CharField(max_length=121)),
                ('phone', models.CharField(max_length=121)),
                ('address', models.CharField(max_length=121)),
                ('donation', models.CharField(max_length=121)),
                ('date', models.DateField()),
            ],
        ),
    ]
