# Generated by Django 5.0.6 on 2024-06-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_contact_delete_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=121)),
                ('email', models.CharField(max_length=121)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=10)),
                ('feedback', models.CharField(max_length=121)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=121)),
                ('email', models.CharField(max_length=121)),
                ('password', models.CharField(max_length=121)),
                ('phone', models.CharField(max_length=121)),
                ('address', models.CharField(max_length=121)),
                ('donation', models.CharField(max_length=121)),
                ('date', models.DateField()),
            ],
        ),
    ]
